!--------------------------------------------------------- -*- fortran -*- ----
!* MasterJobCard for eventType=5 (neutrino induced)
!------------------------------------------------------------------------------
! please visit the GiBUU homepage for further information:
! https://gibuu.hepforge.org
!------------------------------------------------------------------------------
! DON'T  FORGET to change  "path_to_input" in the namelist &input according to your local GiBUU installation
!------------------------------------------------------------------------------
! This jobcard is set up for MINERvA flux, to use another flux change "nuExp" in the namelist &neutrino_induced
!------------------------------------------------------------------------------
! In this jobcard some of the analysis is switched OFF, see namelist &neutrinoAnalysis;
! the output of final events and particles in each event is given to the file FinalEvents.dat
! to turn it OFF switch outputEvents=.false. in the namelist &neutrinoAnalysis
! To produce the output in the LesHouches format to files EventOutput.Pert.*.lhe
! switch WritePerturbativeParticles=T in the namelist &EventOutput
!
!******************************************************************************
! Some hints on output:
!
! for kinetic energy distribution of pions see diff_000_dSigma_dEkin_pi_charge..... .dat  (1 pion in the final state )
! for kinetic energy distribution of nucleons see diff_000_dSigma_dEkin_N_charge..... .dat  (1 pion in the final state )
! for kinetic energy distribution of kaons see diff_000_dSigma_dEkin_K_charge..... .dat  (1 pion in the final state )
!       these files will only be in output if in the namelist &detailed_diff  you set forkaon=.true.
!       the same applies for eta, antikaons, Lambda and Sigma hyperons
! to change the maximal kinetic energy (in the output file only) and binning, change ekinMax and dEkin  in the same namelist
!
! for Q2, outgoing-lepton-kinetic-energy and outgoing-lepton-angle-with-respect-to-neutrino-direction  distributions
!       for "0 pion in the final state" (QE-like) events see  files diff_000_dSigma_ ..... lepton_no_pi.dat
!       These will only appear on the output only if specificEventAnalysis=.true. and  in the namelist &nl_specificEvent you set no_pi=.true.
!       In the same namelist other type of final states can also be choosen, output will be produced for all of them
!
! For energy reconstruction and oscillation analysis for the specific final states, as set in the &nl_specificEvent,
!       set "reconstruct_neutrino_energy=.true. ; for output see files reconstruction....dat   and oscillation....dat
!


!##############################################################################
!init flags
!##############################################################################
!******************************************************************************
! neutrino init:
!******************************************************************************
! file code/init/neutrino/initNeutrino.f90

&neutrino_induced
       process_ID      =  -2 ! 2:CC, 3:NC, -2:antiCC, -3:antiNC
       flavor_ID       =  2 ! 1:electron, 2:muon, 3:tau
!
!       for calculations with given, fixed neutrino energy
!       nuXsectionMode  =  6 !  6: dSigmaMC
! calculation for flux-veraged cross sections (choose with flag nuExp): above  plus 10
       nuXsectionMode  = 16 ! 16: EXP_dSigmaMC
!
! The values for nuExp are ! only relevant if nuXsectionmode.ge.10
!
!       nuExp           =  0 !  0: noExp
!       nuExp           =  1 !  1: MiniBooNE-nu
!       nuExp           =  2 !  2: ANL
!       nuExp           =  3 !  3: K2K
!       nuExp           =  4 !  4: BNL
!       nuExp           =  5 !  5: MinibooNE-barnu
!       nuExp           =  6 !  6: MINOS-numu-numode
!       nuExp           =  7 !  7: MINOS-barnumu-numode
!       nuExp           =  8 !  8: NOvA
!       nuExp           =  9 !  9: T2K-2.5kA-ND280
!       nuExp           = 10 ! 10: uniform-distribution
!       nuExp           = 11 ! 11: MINOS-numu-barnumode
!       nuExp           = 12 ! 12: MINOS-barnumu-barnumode
!       nuExp           = 13 ! 13: MINERvA-nu
!       nuExp           = 14 ! 14: MINERvA-barnu
!       nuExp           = 15 ! 15: DUNE nu
!       nuExp           = 16 ! 16: DUNE barnu
!       nuExp           = 17 ! 17: LBNO
!       nuExp           = 18 ! 18: NOMAD
!       nuExp           = 19 ! 19: BNB nue
!       nuExp           = 20 ! 10: BNB nuebar
!       nuExp           = 21 ! 21: BNB numu
!       nuExp           = 22 ! 22: BNB numubar
! MINERvA, 2016 flux
        nuExp           = 25 
!        nuExp           = 99 ! new, own flux. Must be in buuinput as .dat file
                             ! with 2 columns,
                             ! 1st col: energy, 2nd col: flux,
                             ! energies must be linear and equidistant
                             ! name of the flux file is given in the next line:
!FileNameFlux = '/storage/gpfs_data/juno/junofs/users/mrifai/GiBUU_test/buuinput2021/neutrino/JUNO_flat_neutrinos.dat'
                             ! for nuExp=99
                             ! this is an example for the MINERvA medium energy
                             ! flux, but any other flux could be inserted here


!
       includeQE       = T
       includeDELTA    = T
       includeRES      = T
       include1pi      = T
       includeDIS      = T
       include2p2hQE   = T
       include2p2hDelta= F
       include2pi      = T
/
  
!"Actually, if you do not have these infamous flux-cuts in your analysis then you could just remove the whole nl_fluxcuts alltogether."  2018-07-02
!   Flux cuts
!&nl_fluxcuts
!       Enu_lower_cut    = 0.0
!       Enu_upper_cut    = 50.0
!       energylimit_for_Qsrec = T   ! switch for using fluxcuts also in Q^2 reconstr.
!/
!


! file code/density/nucleus.f90
&target
	target_Z=6
	target_A=12
	densitySwitch_Static=2          ! 0: density=0.0, 1: Woods-Saxon by Lenske, 2 : NPA 554, 3: Woods-Saxon by Lenske, different neutron and proton radii,
					! 5: density distribution is a sphere with density according to the input value of "fermiMomentum_input".
	fermiMomentum_input=0.225       ! Input value of the fermi momentum for densitySwitch_static=5.
	fermiMotion=.true.
	ReAdjustForConstBinding=.true.
  ConstBinding=-0.008             ! binding energy at Fermi surface, only valid for ReAdjustForConstBinding=true
/

! file code/density/density.f90
&initDensity
    densitySwitch=2                 ! 1=dynamic density according to testparticle density, 2=analytic density prescription
/

! file code/density/pauliBlocking.f90
&initPauli
    pauliSwitch=2                   ! 1=dynamic, 2=analytic
/
!##############################################################################
! general input, controls among others the statistics of output
!##############################################################################


! file code/inputOutput/input.f90
! the number of generated events is proportional (but not equal, because some "events" can be in prohibited phase space)
! to target_A * numEnsembles * num_runs_SameEnergy
&input
	numEnsembles=4              ! for C12 you can use 4000, for heavier nuclei should be lower; decrease it if there are problems with memory,
	eventtype=5                     ! 5=neutrino, 200=simple transport of a given particle
!If you are interested in the effects of fsi you have to follow the time-propagation of the particles outgoing from the very first, initial interaction. For C12 a reasonable value is 120
	numTimeSteps=120               ! the distance numTimeSteps*delta_T (100*0.2=20 fm in this example) should significantly exceed the radius of the target nucleus
	delta_T=0.2
	fullensemble=.true.
	localEnsemble=.true.
! 100 runs take 7 mins. So 1h 800 runs, 12.5 hours 10k runs -> 100 times of test_c_2 -> too much!
	num_runs_SameEnergy=1           ! increase these if you want to increase statistics (= number of generated events)
	num_Energies=1                  ! for nuXsectionMode=6 or 16 keep this 1, for other nuXsectionMode this is the number of the running Q2/Elepton/cosTheta variables, respectively
	printParticleVectors=.false.
	freezeRealParticles=.true.
	LRF_equals_CALC_frame=.true.          !if .false.: no offshelltransport possible
	path_to_input='/storage/gpfs_data/juno/junofs/users/mrifai/GiBUU_test/buuinput2021'
/

! file code/init/neutrino/neutrinoXsection.f90
&nl_neutrinoxsection
	singlePiModel=1
        REScutW=2.0
        REScutwidth=0.1
        DIScutW=1.95
        DIScutwidth=0.1
        invariantMasscut=20.
        invariantMasscut_BG=20.

/


! SPECFIC NEUTRINO FLAGS depending on nuXsectionMode
! file for all of them   code/init/neutrino/neutrinoXsection.f90
! relevant for nuXsectionMode=6 and (except parameter enu) 16
&nl_SigmaMC
    MC_xmax=2.0		! to get QE peak in nuclei, where Bjorken_x can be larger than 1
    enu=1.0
/

!##############################################################################
!analysis flags
!##############################################################################


!******************************************************************************
! Neutrino analysis
!******************************************************************************

! file code/init/neutrino/expNeutrinofluxes.f90
&MiniBooNE_energyFlux           !
    Eb=0.030                       ! which binding energy to use in the muon-kinematics-based formular for neutrino energy reconstruction for "0-pion" events
/

! file  code/analysis/neutrinoAnalysis.f90

&neutrinoAnalysis
	radialScale=0
	detailed_diff_output=.false.     ! differential xsec; see namelist detailed_diff for max values and bins of the histograms
	kineticEnergyDetectionThreshold_nucleon=0.
	kineticEnergyDetectionThreshold_chargedpion=0.
	kineticEnergyDetectionThreshold_neutralpion=0.
	calorimetric_analysis=.false.        ! calorimetric reconstruction of energy; see namelist nl_calorimetric_analysis
	ZeroPion_analysis=.false.            ! extra cross sections  for events with 0 pions in the final state
	reconstruct_neutrino_energy=.false.  ! calculate neutrino energy reconstruction for varios final states (see nl_specificEvent)
	specificEvent_analysis=.false.       ! extra cross sections for specific final states; see namelist nl_specificEvent
										                  ! also provides Q2 and energy reconstruction
	inclusiveAnalysis=.false.            !if .true. we don't care whether particles have made it out
	outputEvents=.true.                   ! output list of events and all outgoing particles in each event to the file FinalEvents.dat
!  AngleUpperDetectionThresholdDegrees_lepton = 20.    ! outgoing lepton acceptance cut
!  kineticEnergyDetectionThreshold_lepton=0.0          ! outgoing lepton acceptance cut

  include_W_dist=.false.               !printout of W-distributions for outgoing channel
/

! file code/analysis/EventOutputAnalysis.f90
&EventOutput
!  EventFormat=1 !Les Houches(default), =2 (Oscar), = 3 (Shanghai)
   WritePerturbativeparticles=.false. ! output list of events and all outgoing particles in each event in format specified
/



! file code/analysis/neutrinoAnalysis.f90
&nl_calorimetric_analysis
	numax=30
	nubin=0.02
	Enumax=30
	enubin=0.05
/

! file code/analysis/neutrinoAnalysis.f90
$nl_specificEvent          ! any .true. in this namelist must be combines with specificEvent_analysis=.true. in &neutrinoAnalysis
	no_pi=.false.           ! specificEvent=1        set to .true. if you want produce e.g. one-diff xsec versus lepton varaibles (Ekin, Q2, costheta)
			                   !			                  for "no pions in the final state" events
	p_Xn_no_pi=.false.      ! specificEvent=2
	piplus=.false.          ! specificEvent=3
	pi0=.false.             ! specificEvent=4
	pi0_MULTI=.false.       ! specificEvent=5
	piplus_MULTI=.false.    ! specificEvent=6
	pp_no_pi=.false.       ! specificEvent=7
	pn_no_pi=.false.       ! specificEvent=8
	nn_no_pi=.false.       ! specificEvent=9
	pp_Xn_no_pi=.false.    ! specificEvent=10
	nn_Xp_no_pi=.false.    ! specificEvent=11
	ppp_Xn_no_pi=.false.   ! specificEvent=12
	pppp_Xn_no_pi=.false.  ! specificEvent=13
	p_no_pi=.false. ! specificEvent=14
	n_no_pi=.false. ! specificEvent=15
	Xn_no_pi=.false. ! specificEvent=16
!
!  binning for reconstruction of Q2 and Enu
!
  binsizeQ2=0.01
  binsizeEnu=0.05
  maxQ2=5.0
  maxEnu=8.0
/


! file code/analysis/neutrinoAnalysis.f90
&detailed_diff
	ekinMax=5.0         ! maximum value of Ekin in the output of distribution of hadrons versus kinetic energy
	dEkin=0.02          ! binning of Ekin in the output versus kinetic energy
	fornucleon=.false.   ! produce output versus kinetic energy, angle, ... for this outgoing hadron
	forpion=.false.      ! to the files diff_....
	foreta=.false.
	forkaon=.false.
	forkaonBar=.false.
	forLambda=.false.
	forSigmaResonance=.false.
/


!******************************************************************************
! Model ingredients
!******************************************************************************

! file code/init/lowElectron/lepton2p2h.f90
&lepton2p2h
!  You can override the default T=1 in the code by adding a line with T = 0 in the namelist lepton2p2h May 23
    T=0
    ME_Version=4                    !
/


! file code/init/neutrino/matrixelement.f90
&neutrino_matrixelement
    which_resonanceModel=0          !0=QE + matrixelements from MAID, 1=QE matrixelements + old Delta, 2=Rein-Sehgal
/


! file code/init/lepton/formfactors_QE_nucleon/FF_QE_nucleonScattering.f90
&ff_QE
	parametrization=3               ! 1=BBA03, 2=BBBA05, 3=BBBA07
	useNonStandardMA=.false.        ! if true, use value of MA_in for axial mass MA, if false, use best fit
!   MA_in=1.0
/

!******************************************************************************
! form factors for resonance production
!******************************************************************************
! file code/init/lepton/formfactors_ResProd/formFactor_ResProd.f90
&input_FF_ResProd
  FF_ResProd=0                    ! 0=MAID in CM-frame, 1=fit of Lalakulich ,2=MAID in LAB-frame
  !MA=1.3                         ! axial mass in the Delta resonance form factors based on ANL=0.95 (default)  or BNL=1.3
/

!******************************************************************************
!background parameters for fit to ANL or BNL pion data
!******************************************************************************
! file  code/init/neutrino/singlePionProductionMAIDlike.f90
&neutrino_MAIDlikeBG
!  b_proton_pinull=3.0            ! parameters for 1-pion background  ANL=3   (default)            BNL=6
!  b_neutron_piplus=1.5           !                                   ANL=1.5 (default)            BNL=3.0
/


!##############################################################################
! in-medium width
!##############################################################################

! file code/width/baryonWidthMedium.f90
! "Furthermore, we also run nowadays with free Delta contributions since this is more consistent with the data and the theoretical description of Delta excitation. This is handled by setting all the switches in namelist width_Baryon to false." -- Mosel May 23 2018
&width_Baryon
    mediumSwitch=.false.               ! if .false. vacuum widths will be used for all resonances
                                      ! and other switches are not meaningful/relevant
    mediumSwitch_Delta=.false.         ! Use Oset broadening of the Delta (only relevant for mediumSwitch_coll=.false.)
    mediumSwitch_coll=.false.         ! Use collisional broadening of all resonances
/


! file  code/spectralFunctions/spectralFunc.f90
&spectralFunction
   nuclwidth=0.001                 ! if mediumSwitch_coll=.false.: this parameter determines the "bare nucleon width", for numerical purpose
   relativistic=.true.             ! if mediumSwitch_coll=.false.: relativistic or non-rel. spectral function
/


!##############################################################################
! propagation
!##############################################################################
! file  code/propagation/propagation.f90
&propagation
	RungeKuttaOrder=2                ! 1=first order Runge-Kutta, 2=second order Runge-Kutta
/


! file  code/width/offShellPotential.f90
&offShellPotential
	useOffShellPotentialBaryons=.false.     ! if inMediumSwitch=.false. also useOffShellpotential will be set to .false.
	extrapolateBaryonWidth=.false.          ! whether to extrapolate the baryon width below minimal mass
/


!##############################################################################
! potentials
!##############################################################################
! file code/potential/baryonPotential.f90
&baryonPotential
	EQS_Type=5                      ! 1=soft mom-dep, 2=hard mom-dep, 3=soft non-mom-dep, 4=hard non-mom-dep, 5=medium mom-dep
	DeltaPot=1                      ! 1=2/3 of nucleon potential, 2=100 MeV*rho/rhoNull
/


!##############################################################################
! collision term
!##############################################################################

! file code/collisions/collisionTerm.f90
&collisionTerm
	oneBodyProcesses=.true.
	twoBodyProcesses=.true.
	threeBodyProcesses=.true.
	DoJustAbsorptive=.false.
/


! file  code/collisions/twoBodyReactions/hadronFormation.f90
!&hadronFormation
!   useJetSetVec=.false.  ! use .false. to switch to old JETSET model for hadron formation
!   tauForma=0.01         ! only valid for useJetSetVec=.false. ,   the value 0.01 is equivalent to 0, default is 0.8
!/


! file code/collisions/twoBodyReactions/master_2Body.f90
&master_2Body
	baryonBaryonScattering=.true.
	baryonMesonScattering=.true.
	mesonMesonScattering=.false.
/


!file code/collisions/twoBodyReactions/baryonMeson/resonanceCrossSections.f90
&resonanceCrossSections
	fullPropagator=.false.          ! Use self energies in resonance propagators (only when collisional broadening is switched on)
/



! file code/collisions/insertion.f90
&insertion
    minimumEnergy=0.005  ! default is 0.005 GeV
/


! file code/collisions/twoBodyReactions/HiEnergy/DoCollTools.f90
&pythia
   PARP(91)=0.44
/
